import type { AdminRoom } from './types'
import { roomCategoryLabels } from './types'

const roomHero = '/images/homestay-room-hero.png'

export const MOCK_ADMIN_ROOMS: AdminRoom[] = [
  {
    id: 'room-001',
    code: 'STD-A1',
    name: 'Standard Garden 101',
    category: 'standard',
    categoryLabel: roomCategoryLabels.standard,
    capacity: 4,
    pricePerHour: 120000,
    status: 'active',
    image: roomHero,
    equipmentCount: 6,
    equipments: ['Wi-Fi', 'Điều hòa', 'Smart TV', 'Máy nước nóng'],
    todaySchedule: '09:00-11:00, 18:00-20:00',
    lastUpdated: '27/06/2026 09:15',
    description: 'Phòng homestay sạch sẽ với đầy đủ tiện nghi thiết yếu cho khách lưu trú.',
    occupancyRateToday: 62,
    monthlyRevenue: 18400000,
    averageRating: 4.6,
    latestMaintenance: 'Kiểm tra tiện nghi định kỳ - 22/06/2026',
  },
  {
    id: 'room-002',
    code: 'STD-A2',
    name: 'Standard Garden 102',
    category: 'standard',
    categoryLabel: roomCategoryLabels.standard,
    capacity: 5,
    pricePerHour: 135000,
    status: 'occupied',
    image: roomHero,
    equipmentCount: 7,
    equipments: ['Wi-Fi', 'Điều hòa', 'Smart TV', 'Máy nước nóng'],
    todaySchedule: '10:00-12:00, 15:00-17:00, 19:00-21:00',
    lastUpdated: '27/06/2026 10:45',
    description: 'Phòng homestay sạch sẽ với đầy đủ tiện nghi thiết yếu cho khách lưu trú.',
    occupancyRateToday: 78,
    monthlyRevenue: 21150000,
    averageRating: 4.7,
    latestMaintenance: 'Kiểm tra tiện nghi định kỳ - 22/06/2026',
  },
  {
    id: 'room-003',
    code: 'STD-A3',
    name: 'Standard Garden 103',
    category: 'standard',
    categoryLabel: roomCategoryLabels.standard,
    capacity: 4,
    pricePerHour: 120000,
    status: 'maintenance',
    image: roomHero,
    equipmentCount: 5,
    equipments: ['Wi-Fi', 'Điều hòa', 'Smart TV', 'Máy nước nóng'],
    todaySchedule: 'Đang khóa lịch',
    lastUpdated: '26/06/2026 18:20',
    description: 'Phòng homestay sạch sẽ với đầy đủ tiện nghi thiết yếu cho khách lưu trú.',
    occupancyRateToday: 0,
    monthlyRevenue: 15600000,
    averageRating: 4.4,
    latestMaintenance: 'Kiểm tra tiện nghi định kỳ - 22/06/2026',
  },
  {
    id: 'room-004',
    code: 'BAND-B1',
    name: 'Deluxe Balcony 201',
    category: 'band',
    categoryLabel: roomCategoryLabels.band,
    capacity: 7,
    pricePerHour: 180000,
    status: 'active',
    image: roomHero,
    equipmentCount: 10,
    equipments: ['Wi-Fi', 'Điều hòa', 'Smart TV', 'Máy nước nóng'],
    todaySchedule: '08:00-10:00, 14:00-16:00',
    lastUpdated: '27/06/2026 08:30',
    description: 'Phòng homestay sạch sẽ với đầy đủ tiện nghi thiết yếu cho khách lưu trú.',
    occupancyRateToday: 54,
    monthlyRevenue: 32600000,
    averageRating: 4.8,
    latestMaintenance: 'Kiểm tra tiện nghi định kỳ - 22/06/2026',
  },
  {
    id: 'room-005',
    code: 'BAND-B2',
    name: 'Deluxe City View 202',
    category: 'band',
    categoryLabel: roomCategoryLabels.band,
    capacity: 8,
    pricePerHour: 195000,
    status: 'occupied',
    image: roomHero,
    equipmentCount: 11,
    equipments: ['Wi-Fi', 'Điều hòa', 'Smart TV', 'Máy nước nóng'],
    todaySchedule: '11:00-13:00, 16:00-18:00, 20:00-22:00',
    lastUpdated: '27/06/2026 11:05',
    description: 'Phòng homestay sạch sẽ với đầy đủ tiện nghi thiết yếu cho khách lưu trú.',
    occupancyRateToday: 83,
    monthlyRevenue: 38450000,
    averageRating: 4.9,
    latestMaintenance: 'Kiểm tra tiện nghi định kỳ - 22/06/2026',
  },
  {
    id: 'room-006',
    code: 'BAND-B3',
    name: 'Deluxe Garden 203',
    category: 'band',
    categoryLabel: roomCategoryLabels.band,
    capacity: 6,
    pricePerHour: 170000,
    status: 'active',
    image: roomHero,
    equipmentCount: 9,
    equipments: ['Wi-Fi', 'Điều hòa', 'Smart TV', 'Máy nước nóng'],
    todaySchedule: '13:00-15:00, 18:00-19:00',
    lastUpdated: '26/06/2026 16:40',
    description: 'Phòng homestay sạch sẽ với đầy đủ tiện nghi thiết yếu cho khách lưu trú.',
    occupancyRateToday: 47,
    monthlyRevenue: 27800000,
    averageRating: 4.5,
    latestMaintenance: 'Kiểm tra tiện nghi định kỳ - 22/06/2026',
  },
  {
    id: 'room-007',
    code: 'REC-C1',
    name: 'Family Suite 301',
    category: 'recording',
    categoryLabel: roomCategoryLabels.recording,
    capacity: 5,
    pricePerHour: 260000,
    status: 'active',
    image: roomHero,
    equipmentCount: 14,
    equipments: ['Wi-Fi', 'Điều hòa', 'Smart TV', 'Máy nước nóng'],
    todaySchedule: '09:00-12:00, 17:00-19:00',
    lastUpdated: '27/06/2026 07:50',
    description: 'Phòng homestay sạch sẽ với đầy đủ tiện nghi thiết yếu cho khách lưu trú.',
    occupancyRateToday: 58,
    monthlyRevenue: 42600000,
    averageRating: 4.8,
    latestMaintenance: 'Kiểm tra tiện nghi định kỳ - 22/06/2026',
  },
  {
    id: 'room-008',
    code: 'REC-C2',
    name: 'Family Garden 302',
    category: 'recording',
    categoryLabel: roomCategoryLabels.recording,
    capacity: 4,
    pricePerHour: 240000,
    status: 'inactive',
    image: roomHero,
    equipmentCount: 12,
    equipments: ['Wi-Fi', 'Điều hòa', 'Smart TV', 'Máy nước nóng'],
    todaySchedule: 'Tạm ngưng nhận lịch',
    lastUpdated: '25/06/2026 14:10',
    description: 'Phòng homestay sạch sẽ với đầy đủ tiện nghi thiết yếu cho khách lưu trú.',
    occupancyRateToday: 0,
    monthlyRevenue: 30100000,
    averageRating: 4.3,
    latestMaintenance: 'Kiểm tra tiện nghi định kỳ - 22/06/2026',
  },
  {
    id: 'room-009',
    code: 'REC-C3',
    name: 'Family City 303',
    category: 'recording',
    categoryLabel: roomCategoryLabels.recording,
    capacity: 6,
    pricePerHour: 280000,
    status: 'active',
    image: roomHero,
    equipmentCount: 15,
    equipments: ['Wi-Fi', 'Điều hòa', 'Smart TV', 'Máy nước nóng'],
    todaySchedule: '12:00-15:00',
    lastUpdated: '26/06/2026 20:05',
    description: 'Phòng homestay sạch sẽ với đầy đủ tiện nghi thiết yếu cho khách lưu trú.',
    occupancyRateToday: 42,
    monthlyRevenue: 46800000,
    averageRating: 4.7,
    latestMaintenance: 'Kiểm tra tiện nghi định kỳ - 22/06/2026',
  },
  {
    id: 'room-010',
    code: 'PRE-D1',
    name: 'Family Premium 401',
    category: 'premium',
    categoryLabel: roomCategoryLabels.premium,
    capacity: 9,
    pricePerHour: 340000,
    status: 'active',
    image: roomHero,
    equipmentCount: 18,
    equipments: ['Wi-Fi', 'Điều hòa', 'Smart TV', 'Máy nước nóng'],
    todaySchedule: '10:00-12:00, 19:00-22:00',
    lastUpdated: '27/06/2026 12:00',
    description: 'Phòng homestay sạch sẽ với đầy đủ tiện nghi thiết yếu cho khách lưu trú.',
    occupancyRateToday: 72,
    monthlyRevenue: 58800000,
    averageRating: 4.9,
    latestMaintenance: 'Kiểm tra tiện nghi định kỳ - 22/06/2026',
  },
  {
    id: 'room-011',
    code: 'PRE-D2',
    name: 'Family Premium 402',
    category: 'premium',
    categoryLabel: roomCategoryLabels.premium,
    capacity: 10,
    pricePerHour: 360000,
    status: 'occupied',
    image: roomHero,
    equipmentCount: 20,
    equipments: ['Wi-Fi', 'Điều hòa', 'Smart TV', 'Máy nước nóng'],
    todaySchedule: '08:00-11:00, 14:00-17:00, 18:00-20:00',
    lastUpdated: '27/06/2026 12:35',
    description: 'Phòng homestay sạch sẽ với đầy đủ tiện nghi thiết yếu cho khách lưu trú.',
    occupancyRateToday: 88,
    monthlyRevenue: 64200000,
    averageRating: 4.9,
    latestMaintenance: 'Kiểm tra tiện nghi định kỳ - 22/06/2026',
  },
  {
    id: 'room-012',
    code: 'PRE-D3',
    name: 'Family Premium 403',
    category: 'premium',
    categoryLabel: roomCategoryLabels.premium,
    capacity: 8,
    pricePerHour: 320000,
    status: 'maintenance',
    image: roomHero,
    equipmentCount: 17,
    equipments: ['Wi-Fi', 'Điều hòa', 'Smart TV', 'Máy nước nóng'],
    todaySchedule: 'Đang khóa lịch',
    lastUpdated: '26/06/2026 09:25',
    description: 'Phòng homestay sạch sẽ với đầy đủ tiện nghi thiết yếu cho khách lưu trú.',
    occupancyRateToday: 0,
    monthlyRevenue: 51200000,
    averageRating: 4.6,
    latestMaintenance: 'Kiểm tra tiện nghi định kỳ - 22/06/2026',
  },
]
