CREATE TYPE IF NOT EXISTS role AS ENUM ('CUSTOMER', 'STAFF', 'ADMIN');
CREATE TYPE IF NOT EXISTS room_status AS ENUM ('AVAILABLE', 'IN_USE', 'MAINTENANCE', 'NEED_CLEANING');
CREATE TYPE IF NOT EXISTS facility_condition AS ENUM ('GOOD', 'NEED_CLEANING', 'NEED_CHECK', 'BROKEN');
CREATE TYPE IF NOT EXISTS equipment_type AS ENUM ('WIFI', 'AIR_CONDITIONER', 'TV', 'WATER_HEATER', 'OTHER');
CREATE TYPE IF NOT EXISTS equipment_status AS ENUM ('GOOD', 'BROKEN', 'MAINTENANCE');
CREATE TYPE IF NOT EXISTS booking_status AS ENUM (
    'PENDING_PAYMENT',
    'DEPOSIT_PAID',
    'PAID',
    'CHECKED_IN',
    'COMPLETED',
    'CANCELLED'
);
CREATE TYPE IF NOT EXISTS payment_method AS ENUM ('CASH', 'ONLINE');
CREATE TYPE IF NOT EXISTS payment_provider AS ENUM ('VNPAY', 'SEPAY', 'COUNTER');
CREATE TYPE IF NOT EXISTS payment_transaction_status AS ENUM (
    'INITIALIZED',
    'PENDING',
    'SUCCEEDED',
    'FAILED',
    'CANCELLED'
);
CREATE TYPE IF NOT EXISTS shift_status AS ENUM ('ASSIGNED', 'IN_PROGRESS', 'COMPLETED');
CREATE TYPE IF NOT EXISTS attendance_status AS ENUM ('WORKING', 'DONE', 'MISSING_CHECKOUT');
CREATE TYPE IF NOT EXISTS shift_registration_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

CREATE TABLE IF NOT EXISTS app_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id INT NOT NULL,
    type VARCHAR(60) NOT NULL,
    title VARCHAR(150) NOT NULL,
    content TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS account (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role role NOT NULL,
    email_verified BOOLEAN NOT NULL DEFAULT false,
    email_verification_token_hash VARCHAR(64) UNIQUE,
    email_verification_expires_at TIMESTAMP,
    email_verification_sent_at TIMESTAMP,
    avatar_url VARCHAR(500),
    created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS staff (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INT NOT NULL UNIQUE REFERENCES account(id),
    full_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(50),
    email VARCHAR(255),
    date_of_birth DATE
);

CREATE TABLE IF NOT EXISTS shift (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INT NOT NULL REFERENCES staff(id),
    date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    status shift_status NOT NULL DEFAULT 'ASSIGNED',
    quality_rating INT
);

CREATE TABLE IF NOT EXISTS staff_shift_registration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INT NOT NULL REFERENCES staff(id),
    work_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    status shift_registration_status NOT NULL DEFAULT 'PENDING',
    reviewed_by_account_id INT REFERENCES account(id),
    reviewed_at TIMESTAMP,
    rejection_reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS staff_attendance (
    id UUID PRIMARY KEY,
    staff_id INT NOT NULL REFERENCES staff(id),
    shift_id INT REFERENCES shift(id),
    check_in_time TIMESTAMP NOT NULL,
    check_out_time TIMESTAMP,
    work_duration_hours NUMERIC(8, 2),
    status attendance_status NOT NULL DEFAULT 'WORKING',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS facility_condition_report (
    id UUID PRIMARY KEY,
    staff_id INT NOT NULL REFERENCES staff(id),
    room_id INT NOT NULL,
    equipment_id INT,
    condition facility_condition NOT NULL,
    note VARCHAR(500),
    image_url VARCHAR(500),
    maintenance_suggested BOOLEAN NOT NULL DEFAULT false,
    room_status_after_update room_status,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);
