-- Optional services sold with a stay or requested while the guest is checked in.

ALTER TABLE booking
    ADD COLUMN IF NOT EXISTS room_amount NUMERIC(12, 2),
    ADD COLUMN IF NOT EXISTS addon_amount NUMERIC(12, 2) NOT NULL DEFAULT 0;

UPDATE booking
SET room_amount = ROUND(
        applied_hourly_rate * (EXTRACT(EPOCH FROM (end_time - start_time)) / 3600.0),
        2
    )
WHERE room_amount IS NULL;

UPDATE booking
SET room_amount = total_price
WHERE room_amount IS NULL;

ALTER TABLE booking
    ALTER COLUMN room_amount SET NOT NULL;

ALTER TABLE booking
    DROP CONSTRAINT IF EXISTS chk_booking_room_amount_non_negative,
    DROP CONSTRAINT IF EXISTS chk_booking_addon_amount_non_negative;

ALTER TABLE booking
    ADD CONSTRAINT chk_booking_room_amount_non_negative CHECK (room_amount >= 0),
    ADD CONSTRAINT chk_booking_addon_amount_non_negative CHECK (addon_amount >= 0);

CREATE TABLE IF NOT EXISTS addon_service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    description VARCHAR(500) NOT NULL,
    image_url VARCHAR(500),
    price NUMERIC(12, 2) NOT NULL CHECK (price > 0),
    unit VARCHAR(60) NOT NULL,
    room_tier_id INTEGER REFERENCES room_tier(id),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT chk_addon_service_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT chk_addon_service_description_not_blank CHECK (btrim(description) <> ''),
    CONSTRAINT chk_addon_service_unit_not_blank CHECK (btrim(unit) <> '')
);

CREATE TABLE IF NOT EXISTS booking_addon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INTEGER NOT NULL REFERENCES booking(id) ON DELETE CASCADE,
    addon_service_id BIGINT NOT NULL REFERENCES addon_service(id),
    service_name VARCHAR(120) NOT NULL,
    unit VARCHAR(60) NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price > 0),
    quantity INTEGER NOT NULL CHECK (quantity BETWEEN 1 AND 20),
    total_amount NUMERIC(12, 2) NOT NULL CHECK (total_amount > 0),
    source VARCHAR(20) NOT NULL CHECK (source IN ('BOOKING', 'DURING_STAY')),
    status VARCHAR(30) NOT NULL CHECK (
        status IN ('PENDING_PAYMENT', 'REQUESTED', 'CONFIRMED', 'PREPARED', 'DELIVERED', 'CANCELLED')
    ),
    customer_note VARCHAR(300),
    requested_by_user_id INTEGER REFERENCES account(id),
    confirmed_by_user_id INTEGER REFERENCES account(id),
    delivered_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT chk_booking_addon_delivered_at CHECK (
        status <> 'DELIVERED' OR delivered_at IS NOT NULL
    )
);

CREATE INDEX IF NOT EXISTS idx_addon_service_active_tier
    ON addon_service(active, room_tier_id, name);

CREATE INDEX IF NOT EXISTS idx_booking_addon_booking_status
    ON booking_addon(booking_id, status, created_at);

INSERT INTO addon_service (name, description, price, unit, active)
VALUES
    ('Set BBQ ngoài trời', 'Bếp nướng, vỉ nướng, dụng cụ và phần than cơ bản.', 400000, 'set', TRUE),
    ('Trang trí sinh nhật', 'Trang trí bàn tiệc và không gian phòng theo phong cách The Serene Villa.', 500000, 'lần', TRUE),
    ('Bữa sáng tại phòng', 'Bữa sáng phục vụ tại phòng theo số lượng khách đăng ký.', 100000, 'người', TRUE),
    ('Giường phụ', 'Giường phụ kèm chăn, ga và gối cho một đêm lưu trú.', 300000, 'giường/đêm', TRUE),
    ('Thuê máy chiếu', 'Máy chiếu phục vụ giải trí hoặc sự kiện nhỏ trong thời gian lưu trú.', 250000, 'đêm', TRUE),
    ('Than nướng bổ sung', 'Một túi than nướng bổ sung giao tận phòng.', 50000, 'túi', TRUE)
ON CONFLICT (name) DO NOTHING;

COMMENT ON TABLE addon_service IS 'Admin-managed optional services offered with a homestay booking.';
COMMENT ON TABLE booking_addon IS 'Price snapshots for services selected at booking time or delivered during a stay.';
COMMENT ON COLUMN booking.room_amount IS 'Original room charge before coupon discount and optional services.';
COMMENT ON COLUMN booking.addon_amount IS 'Total optional-service charge currently included in total_price.';
