-- =============================================================
-- Homestay - Script setup database & tao cac bang ban dau
-- Database muc tieu: homestaydb (PostgreSQL)
-- Cach chay:
--   psql -h 127.0.0.1 -p 6789 -U <user> -d homestaydb -f Homestay_Database.sql
-- Script idempotent: chay nhieu lan khong loi (dung IF NOT EXISTS).
-- =============================================================

BEGIN;

-- -------------------------------------------------------------
-- 0. Extension can thiet (EXCLUDE constraint tren range + =)
-- -------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- -------------------------------------------------------------
-- 1. Kieu ENUM
--    CREATE TYPE khong ho tro IF NOT EXISTS -> boc trong DO block.
-- -------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'vai_tro') THEN
    CREATE TYPE "vai_tro" AS ENUM ('CUSTOMER', 'STAFF', 'ADMIN');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'trang_thai_phong') THEN
    CREATE TYPE "trang_thai_phong" AS ENUM ('TRONG', 'DANG_DUNG', 'BAO_TRI');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'trang_thai_dat_phong') THEN
    CREATE TYPE "trang_thai_dat_phong" AS ENUM (
      'CHO_THANH_TOAN', 'DA_THANH_TOAN', 'DA_CHECKIN', 'HOAN_TAT', 'DA_HUY'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'phuong_thuc_thanh_toan') THEN
    CREATE TYPE "phuong_thuc_thanh_toan" AS ENUM ('TIEN_MAT', 'ONLINE');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'cong_thanh_toan') THEN
    CREATE TYPE "cong_thanh_toan" AS ENUM ('VNPAY');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'trang_thai_giao_dich') THEN
    CREATE TYPE "trang_thai_giao_dich" AS ENUM (
      'KHOI_TAO', 'CHO_THANH_TOAN', 'THANH_CONG', 'THAT_BAI', 'DA_HUY'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'loai_giam_gia') THEN
    CREATE TYPE "loai_giam_gia" AS ENUM ('PHAN_TRAM', 'SO_TIEN');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'trang_thai_ca') THEN
    CREATE TYPE "trang_thai_ca" AS ENUM ('DA_PHAN', 'DANG_LAM', 'HOAN_TAT');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'loai_thiet_bi') THEN
    CREATE TYPE "loai_thiet_bi" AS ENUM (
      'WIFI', 'AIR_CONDITIONER', 'TV', 'WATER_HEATER', 'KHAC'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'trang_thai_thiet_bi') THEN
    CREATE TYPE "trang_thai_thiet_bi" AS ENUM ('TOT', 'HONG', 'BAO_TRI');
  END IF;
END
$$;

-- -------------------------------------------------------------
-- 2. Bang
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "tai_khoan" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "mat_khau_hash" varchar NOT NULL,
  "vai_tro" vai_tro NOT NULL,
  "reset_token" varchar UNIQUE,
  "reset_token_expires_at" timestamp,
  "ngay_tao" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "revoked_token" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "token_hash" varchar(64) UNIQUE NOT NULL,
  "expires_at" timestamp NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "khach_hang" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tai_khoan_id" int UNIQUE NOT NULL,
  "ho_ten" varchar NOT NULL,
  "so_dien_thoai" varchar,
  "email" varchar,
  "ngay_sinh" date
);

CREATE TABLE IF NOT EXISTS "nhan_vien" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tai_khoan_id" int UNIQUE NOT NULL,
  "ho_ten" varchar NOT NULL,
  "so_dien_thoai" varchar,
  "email" varchar,
  "ngay_sinh" date
);

CREATE TABLE IF NOT EXISTS "hang_phong" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ten_hang" varchar UNIQUE NOT NULL,
  "gia_gio" numeric(12,2) NOT NULL,
  "mo_ta" text,
  CONSTRAINT "chk_hang_phong_gia_gio_duong" CHECK ("gia_gio" > 0)
);

CREATE TABLE IF NOT EXISTS "phong" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ten" varchar UNIQUE NOT NULL,
  "hang_phong_id" int NOT NULL,
  "trang_thai" trang_thai_phong NOT NULL DEFAULT 'TRONG'
);

CREATE TABLE IF NOT EXISTS "thiet_bi" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phong_id" int NOT NULL,
  "loai" loai_thiet_bi NOT NULL,
  "ten" varchar NOT NULL,
  "trang_thai" trang_thai_thiet_bi NOT NULL DEFAULT 'TOT',
  "ghi_chu" text
);

CREATE TABLE IF NOT EXISTS "ma_giam_gia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ma" varchar UNIQUE NOT NULL,
  "loai" loai_giam_gia NOT NULL,
  "gia_tri" numeric(12,2) NOT NULL,
  "dieu_kien_min" numeric(12,2),
  "ngay_het_han" date,
  CONSTRAINT "chk_ma_giam_gia_gia_tri_duong" CHECK ("gia_tri" > 0),
  CONSTRAINT "chk_ma_giam_gia_phan_tram" CHECK (
    "loai" <> 'PHAN_TRAM' OR "gia_tri" <= 100
  ),
  CONSTRAINT "chk_ma_giam_gia_dieu_kien_min" CHECK (
    "dieu_kien_min" IS NULL OR "dieu_kien_min" >= 0
  )
);

CREATE TABLE IF NOT EXISTS "dat_phong" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "khach_hang_id" int NOT NULL,
  "phong_id" int NOT NULL,
  "ma_giam_gia_id" int,
  "nhan_vien_checkin_id" int,
  "gio_bat_dau" timestamp NOT NULL,
  "gio_ket_thuc" timestamp NOT NULL,
  "gio_checkin" timestamp,
  "gio_checkout" timestamp,
  "phuong_thuc" phuong_thuc_thanh_toan NOT NULL,
  "gia_gio_ap_dung" numeric(12,2) NOT NULL,
  "tong_tien" numeric(12,2) NOT NULL,
  "trang_thai" trang_thai_dat_phong NOT NULL DEFAULT 'CHO_THANH_TOAN',
  "ghi_chu_nhac_cu" varchar(500),
  "ghi_chu" varchar(500),
  "ngay_tao" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT "chk_dat_phong_khoang_thoi_gian" CHECK (
    "gio_bat_dau" < "gio_ket_thuc"
  ),
  CONSTRAINT "chk_dat_phong_gia_gio_ap_dung" CHECK (
    "gia_gio_ap_dung" > 0
  ),
  CONSTRAINT "chk_dat_phong_tong_tien" CHECK ("tong_tien" >= 0),
  CONSTRAINT "chk_dat_phong_checkin_checkout" CHECK (
    "gio_checkout" IS NULL
    OR ("gio_checkin" IS NOT NULL AND "gio_checkin" <= "gio_checkout")
  )
);

CREATE TABLE IF NOT EXISTS "giao_dich_thanh_toan" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dat_phong_id" int NOT NULL,
  "cong_thanh_toan" cong_thanh_toan NOT NULL,
  "ma_giao_dich" varchar(100) UNIQUE NOT NULL,
  "ma_giao_dich_cong" varchar(100) UNIQUE,
  "so_tien" numeric(12,2) NOT NULL,
  "trang_thai" trang_thai_giao_dich NOT NULL DEFAULT 'KHOI_TAO',
  "ma_phan_hoi" varchar(20),
  "thoi_gian_thanh_toan" timestamp,
  "ngay_tao" timestamp NOT NULL DEFAULT (now()),
  "ngay_cap_nhat" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT "chk_giao_dich_so_tien_khong_am" CHECK ("so_tien" >= 0)
);

CREATE TABLE IF NOT EXISTS "lich_su_trang_thai_dat_phong" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dat_phong_id" int NOT NULL,
  "trang_thai_cu" trang_thai_dat_phong,
  "trang_thai_moi" trang_thai_dat_phong NOT NULL,
  "ghi_chu" varchar(500),
  "thoi_gian" timestamp NOT NULL DEFAULT (now()),
  "thuc_hien_boi" int
);

CREATE TABLE IF NOT EXISTS "danh_gia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dat_phong_id" int UNIQUE NOT NULL,
  "diem" int NOT NULL,
  "noi_dung" text,
  "da_duyet" boolean NOT NULL DEFAULT true,
  "ngay_tao" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT "chk_danh_gia_diem" CHECK ("diem" BETWEEN 1 AND 5)
);

CREATE TABLE IF NOT EXISTS "ca_lam" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nhan_vien_id" int NOT NULL,
  "ngay" date NOT NULL,
  "gio_bat_dau" time NOT NULL,
  "gio_ket_thuc" time NOT NULL,
  "trang_thai" trang_thai_ca NOT NULL DEFAULT 'DA_PHAN',
  "diem_chat_luong" int,
  CONSTRAINT "chk_ca_lam_khoang_thoi_gian" CHECK (
    "gio_bat_dau" < "gio_ket_thuc"
  ),
  CONSTRAINT "chk_ca_lam_diem_chat_luong" CHECK (
    "diem_chat_luong" IS NULL OR "diem_chat_luong" BETWEEN 1 AND 5
  )
);

-- -------------------------------------------------------------
-- 3. Index
-- -------------------------------------------------------------
CREATE INDEX IF NOT EXISTS "idx_thiet_bi_phong_loai"
  ON "thiet_bi" ("phong_id", "loai");

CREATE INDEX IF NOT EXISTS "idx_dat_phong_phong_thoi_gian"
  ON "dat_phong" ("phong_id", "gio_bat_dau", "gio_ket_thuc");

CREATE INDEX IF NOT EXISTS "idx_dat_phong_khach_hang_ngay_tao"
  ON "dat_phong" ("khach_hang_id", "ngay_tao" DESC);

CREATE INDEX IF NOT EXISTS "idx_dat_phong_trang_thai_gio_bat_dau"
  ON "dat_phong" ("trang_thai", "gio_bat_dau");

CREATE INDEX IF NOT EXISTS "idx_lich_su_dat_phong_thoi_gian"
  ON "lich_su_trang_thai_dat_phong" ("dat_phong_id", "thoi_gian");

CREATE INDEX IF NOT EXISTS "idx_ca_lam_nhan_vien_ngay"
  ON "ca_lam" ("nhan_vien_id", "ngay");

CREATE INDEX IF NOT EXISTS "idx_revoked_token_expires_at"
  ON "revoked_token" ("expires_at");

-- -------------------------------------------------------------
-- 4. EXCLUDE constraint (chong trung lich)
--    ADD CONSTRAINT khong ho tro IF NOT EXISTS -> boc trong DO block.
-- -------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'excl_dat_phong_khong_trung_lich'
  ) THEN
    ALTER TABLE "dat_phong"
      ADD CONSTRAINT "excl_dat_phong_khong_trung_lich"
      EXCLUDE USING gist (
        "phong_id" WITH =,
        tsrange("gio_bat_dau", "gio_ket_thuc", '[)') WITH &&
      )
      WHERE ("trang_thai" <> 'DA_HUY');
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'excl_ca_lam_nhan_vien_khong_trung'
  ) THEN
    ALTER TABLE "ca_lam"
      ADD CONSTRAINT "excl_ca_lam_nhan_vien_khong_trung"
      EXCLUDE USING gist (
        "nhan_vien_id" WITH =,
        tsrange("ngay" + "gio_bat_dau", "ngay" + "gio_ket_thuc", '[)') WITH &&
      );
  END IF;
END
$$;

-- -------------------------------------------------------------
-- 5. Khoa ngoai
--    Boc trong DO block de chay lai khong bi loi trung ten.
-- -------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_khach_hang_tai_khoan') THEN
    ALTER TABLE "khach_hang" ADD CONSTRAINT "fk_khach_hang_tai_khoan"
      FOREIGN KEY ("tai_khoan_id") REFERENCES "tai_khoan" ("id") DEFERRABLE INITIALLY IMMEDIATE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_nhan_vien_tai_khoan') THEN
    ALTER TABLE "nhan_vien" ADD CONSTRAINT "fk_nhan_vien_tai_khoan"
      FOREIGN KEY ("tai_khoan_id") REFERENCES "tai_khoan" ("id") DEFERRABLE INITIALLY IMMEDIATE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_phong_hang_phong') THEN
    ALTER TABLE "phong" ADD CONSTRAINT "fk_phong_hang_phong"
      FOREIGN KEY ("hang_phong_id") REFERENCES "hang_phong" ("id") DEFERRABLE INITIALLY IMMEDIATE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_thiet_bi_phong') THEN
    ALTER TABLE "thiet_bi" ADD CONSTRAINT "fk_thiet_bi_phong"
      FOREIGN KEY ("phong_id") REFERENCES "phong" ("id") DEFERRABLE INITIALLY IMMEDIATE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_dat_phong_khach_hang') THEN
    ALTER TABLE "dat_phong" ADD CONSTRAINT "fk_dat_phong_khach_hang"
      FOREIGN KEY ("khach_hang_id") REFERENCES "khach_hang" ("id") DEFERRABLE INITIALLY IMMEDIATE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_dat_phong_phong') THEN
    ALTER TABLE "dat_phong" ADD CONSTRAINT "fk_dat_phong_phong"
      FOREIGN KEY ("phong_id") REFERENCES "phong" ("id") DEFERRABLE INITIALLY IMMEDIATE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_dat_phong_ma_giam_gia') THEN
    ALTER TABLE "dat_phong" ADD CONSTRAINT "fk_dat_phong_ma_giam_gia"
      FOREIGN KEY ("ma_giam_gia_id") REFERENCES "ma_giam_gia" ("id") DEFERRABLE INITIALLY IMMEDIATE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_dat_phong_nhan_vien_checkin') THEN
    ALTER TABLE "dat_phong" ADD CONSTRAINT "fk_dat_phong_nhan_vien_checkin"
      FOREIGN KEY ("nhan_vien_checkin_id") REFERENCES "nhan_vien" ("id") DEFERRABLE INITIALLY IMMEDIATE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_giao_dich_dat_phong') THEN
    ALTER TABLE "giao_dich_thanh_toan" ADD CONSTRAINT "fk_giao_dich_dat_phong"
      FOREIGN KEY ("dat_phong_id") REFERENCES "dat_phong" ("id") DEFERRABLE INITIALLY IMMEDIATE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_lich_su_dat_phong') THEN
    ALTER TABLE "lich_su_trang_thai_dat_phong" ADD CONSTRAINT "fk_lich_su_dat_phong"
      FOREIGN KEY ("dat_phong_id") REFERENCES "dat_phong" ("id") DEFERRABLE INITIALLY IMMEDIATE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_lich_su_thuc_hien_boi') THEN
    ALTER TABLE "lich_su_trang_thai_dat_phong" ADD CONSTRAINT "fk_lich_su_thuc_hien_boi"
      FOREIGN KEY ("thuc_hien_boi") REFERENCES "tai_khoan" ("id") DEFERRABLE INITIALLY IMMEDIATE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_danh_gia_dat_phong') THEN
    ALTER TABLE "danh_gia" ADD CONSTRAINT "fk_danh_gia_dat_phong"
      FOREIGN KEY ("dat_phong_id") REFERENCES "dat_phong" ("id") DEFERRABLE INITIALLY IMMEDIATE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ca_lam_nhan_vien') THEN
    ALTER TABLE "ca_lam" ADD CONSTRAINT "fk_ca_lam_nhan_vien"
      FOREIGN KEY ("nhan_vien_id") REFERENCES "nhan_vien" ("id") DEFERRABLE INITIALLY IMMEDIATE;
  END IF;
END
$$;

-- -------------------------------------------------------------
-- 6. Comment mo ta cot
-- -------------------------------------------------------------
COMMENT ON COLUMN "hang_phong"."gia_gio" IS 'Giá thuê / giờ';
COMMENT ON COLUMN "thiet_bi"."ten" IS 'Tên tiện nghi cụ thể, vd: Wi-Fi 5G, Smart TV 50 inch';
COMMENT ON COLUMN "ma_giam_gia"."dieu_kien_min" IS 'Giá trị đơn tối thiểu';
COMMENT ON COLUMN "dat_phong"."ma_giam_gia_id" IS 'Có thể null';
COMMENT ON COLUMN "dat_phong"."nhan_vien_checkin_id" IS 'NV xử lý check-in, có thể null';
COMMENT ON COLUMN "dat_phong"."gia_gio_ap_dung" IS 'Giá giờ tại thời điểm đặt';
COMMENT ON COLUMN "dat_phong"."ghi_chu_nhac_cu" IS 'Tiện nghi phòng khách yêu cầu nhân viên chuẩn bị';
COMMENT ON COLUMN "dat_phong"."ghi_chu" IS 'Ghi chú khác của khách hoặc nhân viên';
COMMENT ON COLUMN "lich_su_trang_thai_dat_phong"."thuc_hien_boi" IS 'tai_khoan.id của người thực hiện thay đổi; null nếu do hệ thống tự động';
COMMENT ON COLUMN "danh_gia"."diem" IS '1-5';
COMMENT ON COLUMN "ca_lam"."diem_chat_luong" IS 'Admin đánh giá ca, 1-5';

-- -------------------------------------------------------------
-- 7. Tai khoan admin mac dinh cho moi truong local/dev
--    Email: admin@homestay.local
--    Password: Admin@123
-- -------------------------------------------------------------
INSERT INTO "tai_khoan" ("email", "mat_khau_hash", "vai_tro")
VALUES (
  'admin@homestay.local',
  '$2a$10$GvWVKahyW48qvHRAsjGbYOXoFz3b/cDSykbxByfHGnCFw/oIvOuZS',
  'ADMIN'
)
ON CONFLICT ("email") DO UPDATE
SET
  "mat_khau_hash" = EXCLUDED."mat_khau_hash",
  "vai_tro" = EXCLUDED."vai_tro";

COMMIT;
