-- =============================================================
-- Homestay Booking Management - canonical PostgreSQL runtime schema
-- Fresh installations use English snake_case names from the start.
-- Legacy installations must use the dated rename/content migrations.
-- =============================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'role') THEN
    CREATE TYPE role AS ENUM ('CUSTOMER', 'STAFF', 'ADMIN');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'room_status') THEN
    CREATE TYPE room_status AS ENUM ('AVAILABLE', 'IN_USE', 'MAINTENANCE', 'NEED_CLEANING', 'INACTIVE');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'booking_status') THEN
    CREATE TYPE booking_status AS ENUM (
      'PENDING_PAYMENT', 'DEPOSIT_PAID', 'PAID', 'CHECKED_IN', 'COMPLETED', 'CANCELLED'
    );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_method') THEN
    CREATE TYPE payment_method AS ENUM ('CASH', 'ONLINE');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_provider') THEN
    CREATE TYPE payment_provider AS ENUM ('VNPAY', 'SEPAY', 'COUNTER');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_transaction_status') THEN
    CREATE TYPE payment_transaction_status AS ENUM (
      'INITIALIZED', 'PENDING', 'SUCCEEDED', 'FAILED', 'CANCELLED'
    );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'discount_type') THEN
    CREATE TYPE discount_type AS ENUM ('PERCENTAGE', 'FIXED_AMOUNT');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'shift_status') THEN
    CREATE TYPE shift_status AS ENUM ('ASSIGNED', 'IN_PROGRESS', 'COMPLETED');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'equipment_type') THEN
    CREATE TYPE equipment_type AS ENUM ('WIFI', 'AIR_CONDITIONER', 'TV', 'WATER_HEATER', 'OTHER');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'equipment_status') THEN
    CREATE TYPE equipment_status AS ENUM ('GOOD', 'BROKEN', 'MAINTENANCE');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'shift_registration_status') THEN
    CREATE TYPE shift_registration_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'attendance_status') THEN
    CREATE TYPE attendance_status AS ENUM ('WORKING', 'DONE', 'MISSING_CHECKOUT');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'facility_condition') THEN
    CREATE TYPE facility_condition AS ENUM ('GOOD', 'NEED_CLEANING', 'NEED_CHECK', 'BROKEN');
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS account (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR UNIQUE NOT NULL,
  password_hash VARCHAR NOT NULL,
  role role NOT NULL,
  credentials_version INTEGER NOT NULL DEFAULT 0,
  reset_token VARCHAR UNIQUE,
  reset_token_expires_at TIMESTAMP,
  email_verified BOOLEAN NOT NULL DEFAULT false,
  enabled BOOLEAN NOT NULL DEFAULT true,
  email_verification_token_hash VARCHAR(64) UNIQUE,
  email_verification_expires_at TIMESTAMP,
  email_verification_sent_at TIMESTAMP,
  avatar_url VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT chk_account_credentials_version
    CHECK (credentials_version >= 0),
  CONSTRAINT chk_account_avatar_url_length
    CHECK (avatar_url IS NULL OR char_length(avatar_url) <= 500)
);

CREATE TABLE IF NOT EXISTS revoked_token (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash VARCHAR(64) UNIQUE NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS customer (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INT UNIQUE NOT NULL REFERENCES account(id),
  full_name VARCHAR NOT NULL,
  phone_number VARCHAR,
  email VARCHAR,
  date_of_birth DATE
);

CREATE TABLE IF NOT EXISTS staff (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INT UNIQUE NOT NULL REFERENCES account(id),
  full_name VARCHAR NOT NULL,
  phone_number VARCHAR,
  email VARCHAR,
  date_of_birth DATE
);

CREATE TABLE IF NOT EXISTS room_tier (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR UNIQUE NOT NULL,
  hourly_rate NUMERIC(12,2) NOT NULL,
  description TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT chk_room_tier_hourly_rate_positive CHECK (hourly_rate > 0)
);

CREATE TABLE IF NOT EXISTS room (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR UNIQUE NOT NULL,
  room_tier_id INT NOT NULL REFERENCES room_tier(id),
  max_people INT NOT NULL DEFAULT 2,
  status room_status NOT NULL DEFAULT 'AVAILABLE',
  image_url VARCHAR(500),
  image_url_2 VARCHAR(500),
  image_url_3 VARCHAR(500),
  image_url_4 VARCHAR(500),
  CONSTRAINT chk_room_max_people_range CHECK (max_people BETWEEN 1 AND 100),
  CONSTRAINT chk_room_image_url_length CHECK (image_url IS NULL OR char_length(image_url) <= 500)
);

CREATE TABLE IF NOT EXISTS common_amenity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  description VARCHAR(500) NOT NULL,
  icon_name VARCHAR(60) NOT NULL,
  image_url VARCHAR(500),
  display_order INT NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS equipment (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id INT NOT NULL REFERENCES room(id),
  type equipment_type NOT NULL,
  name VARCHAR NOT NULL,
  status equipment_status NOT NULL DEFAULT 'GOOD',
  notes TEXT
);

CREATE TABLE IF NOT EXISTS discount_code (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR UNIQUE NOT NULL,
  type discount_type NOT NULL,
  value NUMERIC(12,2) NOT NULL,
  min_order_value NUMERIC(12,2),
  expires_at DATE,
  CONSTRAINT chk_discount_code_value_positive CHECK (value > 0),
  CONSTRAINT chk_discount_code_percentage_value CHECK (type <> 'PERCENTAGE' OR value <= 100),
  CONSTRAINT chk_discount_code_min_order_value_non_negative
    CHECK (min_order_value IS NULL OR min_order_value >= 0)
);

CREATE TABLE IF NOT EXISTS booking (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INT NOT NULL REFERENCES customer(id),
  room_id INT NOT NULL REFERENCES room(id),
  discount_code_id INT REFERENCES discount_code(id),
  checkin_staff_id INT REFERENCES staff(id),
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  checkin_time TIMESTAMP,
  checkout_time TIMESTAMP,
  payment_method payment_method NOT NULL,
  applied_hourly_rate NUMERIC(12,2) NOT NULL,
  total_price NUMERIC(12,2) NOT NULL,
  status booking_status NOT NULL DEFAULT 'PENDING_PAYMENT',
  equipment_notes VARCHAR(500),
  notes VARCHAR(500),
  cancellation_request_status VARCHAR(20),
  cancellation_reason VARCHAR(500),
  cancellation_requested_at TIMESTAMP,
  cancellation_reviewed_at TIMESTAMP,
  cancellation_reviewed_by VARCHAR(255),
  cancellation_admin_note VARCHAR(500),
  refund_amount NUMERIC(12,2),
  refund_percentage INT,
  refund_method VARCHAR(100),
  expected_refund_at TIMESTAMP,
  refund_bank_code VARCHAR(20),
  refund_bank_name VARCHAR(100),
  refund_account_number VARCHAR(30),
  refund_account_holder VARCHAR(100),
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT chk_booking_time_range CHECK (start_time < end_time),
  CONSTRAINT chk_booking_applied_hourly_rate_positive CHECK (applied_hourly_rate > 0),
  CONSTRAINT chk_booking_total_price_non_negative CHECK (total_price >= 0),
  CONSTRAINT ck_booking_cancellation_request_status
    CHECK (cancellation_request_status IS NULL OR cancellation_request_status IN ('PENDING', 'APPROVED', 'REJECTED')),
  CONSTRAINT ck_booking_refund_percentage
    CHECK (refund_percentage IS NULL OR refund_percentage BETWEEN 0 AND 100),
  CONSTRAINT ck_booking_refund_amount
    CHECK (refund_amount IS NULL OR refund_amount >= 0),
  CONSTRAINT chk_booking_checkin_checkout
    CHECK (checkout_time IS NULL OR (checkin_time IS NOT NULL AND checkin_time <= checkout_time))
);

CREATE INDEX IF NOT EXISTS idx_booking_pending_cancellation_request
  ON booking (cancellation_requested_at DESC)
  WHERE cancellation_request_status = 'PENDING';

CREATE TABLE IF NOT EXISTS favorite_room (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INT NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  room_id INT NOT NULL REFERENCES room(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT uq_favorite_room_account_room UNIQUE (account_id, room_id)
);

CREATE INDEX IF NOT EXISTS idx_favorite_room_account_created_at
  ON favorite_room (account_id, created_at DESC);

CREATE TABLE IF NOT EXISTS payment_transaction (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id INT NOT NULL REFERENCES booking(id),
  provider payment_provider NOT NULL,
  transaction_reference VARCHAR(100) UNIQUE NOT NULL,
  provider_transaction_id VARCHAR(100) UNIQUE,
  amount NUMERIC(12,2) NOT NULL,
  status payment_transaction_status NOT NULL DEFAULT 'INITIALIZED',
  response_code VARCHAR(50),
  paid_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT chk_payment_transaction_amount_non_negative CHECK (amount >= 0)
);

CREATE TABLE IF NOT EXISTS booking_refund (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id INT NOT NULL REFERENCES booking(id),
  original_payment_transaction_id BIGINT REFERENCES payment_transaction(id),
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  recipient_bank_code VARCHAR(20),
  recipient_bank_name VARCHAR(100),
  recipient_account_number VARCHAR(30),
  recipient_account_holder VARCHAR(100),
  method VARCHAR(40) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  transaction_reference VARCHAR(100),
  proof_image_url VARCHAR(1000),
  admin_note VARCHAR(500),
  failure_reason VARCHAR(500),
  processed_by VARCHAR(255),
  expected_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  processing_at TIMESTAMP,
  completed_at TIMESTAMP,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_booking_refund_booking UNIQUE (booking_id),
  CONSTRAINT uk_booking_refund_reference UNIQUE (transaction_reference),
  CONSTRAINT ck_booking_refund_method CHECK (method IN ('ORIGINAL_PAYMENT_METHOD', 'MANUAL_BANK_TRANSFER', 'CASH_COUNTER')),
  CONSTRAINT ck_booking_refund_status CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'RETRY_REQUIRED')),
  CONSTRAINT ck_booking_refund_completed CHECK (status <> 'COMPLETED' OR (completed_at IS NOT NULL AND transaction_reference IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS idx_booking_refund_status_created
  ON booking_refund(status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_booking_refund_expected
  ON booking_refund(expected_at)
  WHERE status IN ('PENDING', 'PROCESSING', 'RETRY_REQUIRED');

CREATE TABLE IF NOT EXISTS booking_status_history (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id INT NOT NULL REFERENCES booking(id),
  old_status booking_status,
  new_status booking_status NOT NULL,
  notes VARCHAR(500),
  changed_at TIMESTAMP NOT NULL DEFAULT now(),
  changed_by INT REFERENCES account(id)
);

CREATE TABLE IF NOT EXISTS review (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id INT UNIQUE NOT NULL REFERENCES booking(id),
  rating INT NOT NULL,
  content TEXT,
  approved BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT chk_review_rating_range CHECK (rating BETWEEN 1 AND 5)
);

CREATE TABLE IF NOT EXISTS review_image (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id INT NOT NULL REFERENCES review(id) ON DELETE CASCADE,
  image_url VARCHAR(500) NOT NULL,
  display_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT chk_review_image_display_order CHECK (display_order BETWEEN 0 AND 3)
);

CREATE INDEX IF NOT EXISTS idx_review_image_review_display_order
  ON review_image(review_id, display_order, id);

CREATE TABLE IF NOT EXISTS "shift" (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id INT NOT NULL REFERENCES staff(id),
  date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  status shift_status NOT NULL DEFAULT 'ASSIGNED',
  quality_rating INT,
  CONSTRAINT chk_shift_time_range CHECK (start_time < end_time),
  CONSTRAINT chk_shift_quality_rating_range
    CHECK (quality_rating IS NULL OR quality_rating BETWEEN 1 AND 5)
);

CREATE TABLE IF NOT EXISTS review_response (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id INT UNIQUE NOT NULL REFERENCES review(id) ON DELETE CASCADE,
  responder_id INT NOT NULL REFERENCES account(id) ON DELETE RESTRICT,
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS coupon_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  discount_code_id INT NOT NULL REFERENCES discount_code(id),
  customer_id INT NOT NULL REFERENCES customer(id),
  booking_id INT UNIQUE NOT NULL REFERENCES booking(id),
  discount_amount NUMERIC(12,2) NOT NULL,
  used_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT chk_coupon_usage_discount_amount_non_negative CHECK (discount_amount >= 0)
);

CREATE TABLE IF NOT EXISTS customer_issue_report (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INT NOT NULL REFERENCES customer(id),
  booking_id INT REFERENCES booking(id),
  issue_type VARCHAR(30) NOT NULL,
  description VARCHAR(1000) NOT NULL,
  admin_note VARCHAR(1000),
  status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT chk_customer_issue_report_issue_type
    CHECK (issue_type IN ('ROOM', 'EQUIPMENT', 'PAYMENT', 'ACCOUNT', 'OTHER')),
  CONSTRAINT chk_customer_issue_report_status
    CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')),
  CONSTRAINT chk_customer_issue_report_description_not_blank CHECK (btrim(description) <> '')
);

CREATE TABLE IF NOT EXISTS user_notification_settings (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INT UNIQUE NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  new_booking BOOLEAN NOT NULL DEFAULT true,
  booking_reminder BOOLEAN NOT NULL DEFAULT true,
  shift_reminder BOOLEAN NOT NULL DEFAULT true,
  room_issue BOOLEAN NOT NULL DEFAULT true,
  equipment_issue BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS app_notification (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id INT NOT NULL REFERENCES account(id),
  type VARCHAR(60) NOT NULL,
  title VARCHAR(150) NOT NULL,
  content TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT false,
  is_resolved BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS staff_shift_registration (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id INT NOT NULL REFERENCES staff(id),
  work_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  status shift_registration_status NOT NULL DEFAULT 'PENDING',
  reviewed_by_account_id INT REFERENCES account(id),
  reviewed_at TIMESTAMP,
  rejection_reason VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT chk_staff_shift_registration_time_range CHECK (start_time < end_time),
  CONSTRAINT chk_staff_shift_registration_decision_fields CHECK (
    (status = 'PENDING' AND reviewed_by_account_id IS NULL AND reviewed_at IS NULL AND rejection_reason IS NULL)
    OR (status = 'APPROVED' AND reviewed_by_account_id IS NOT NULL AND reviewed_at IS NOT NULL AND rejection_reason IS NULL)
    OR (status = 'REJECTED' AND reviewed_by_account_id IS NOT NULL AND reviewed_at IS NOT NULL
        AND rejection_reason IS NOT NULL AND btrim(rejection_reason) <> '')
  )
);

CREATE TABLE IF NOT EXISTS staff_attendance (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  staff_id INT NOT NULL REFERENCES staff(id),
  shift_id INT REFERENCES "shift"(id),
  check_in_time TIMESTAMP NOT NULL,
  check_out_time TIMESTAMP,
  work_duration_hours NUMERIC(8,2),
  status attendance_status NOT NULL DEFAULT 'WORKING',
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT chk_staff_attendance_checkout_after_checkin
    CHECK (check_out_time IS NULL OR check_out_time > check_in_time),
  CONSTRAINT chk_staff_attendance_duration_non_negative
    CHECK (work_duration_hours IS NULL OR work_duration_hours >= 0)
);

CREATE TABLE IF NOT EXISTS facility_condition_report (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  staff_id INT NOT NULL REFERENCES staff(id),
  room_id INT NOT NULL REFERENCES room(id),
  equipment_id INT REFERENCES equipment(id),
  condition facility_condition NOT NULL,
  note VARCHAR(500),
  image_url VARCHAR(500),
  maintenance_suggested BOOLEAN NOT NULL DEFAULT false,
  room_status_after_update room_status,
  status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
  admin_note VARCHAR(1000),
  resolved_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT chk_facility_condition_report_broken_note
    CHECK (condition <> 'BROKEN' OR (note IS NOT NULL AND btrim(note) <> '')),
  CONSTRAINT chk_facility_condition_report_status
    CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')),
  CONSTRAINT chk_facility_condition_report_note_length
    CHECK (note IS NULL OR char_length(note) <= 500),
  CONSTRAINT chk_facility_condition_report_image_url_length
    CHECK (image_url IS NULL OR char_length(image_url) <= 500),
  CONSTRAINT chk_facility_condition_report_admin_note_length
    CHECK (admin_note IS NULL OR char_length(admin_note) <= 1000)
);

CREATE INDEX IF NOT EXISTS idx_equipment_room_type ON equipment(room_id, type);
CREATE INDEX IF NOT EXISTS idx_booking_room_start_end ON booking(room_id, start_time, end_time);
CREATE INDEX IF NOT EXISTS idx_booking_customer_created_at ON booking(customer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_booking_status_start_time ON booking(status, start_time);
CREATE INDEX IF NOT EXISTS idx_payment_transaction_status_paid_at
  ON payment_transaction(status, paid_at) WHERE paid_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_booking_status_history_booking_changed_at
  ON booking_status_history(booking_id, changed_at);
CREATE INDEX IF NOT EXISTS idx_shift_staff_date ON "shift"(staff_id, date);
CREATE INDEX IF NOT EXISTS idx_revoked_token_expires_at ON revoked_token(expires_at);
CREATE INDEX IF NOT EXISTS idx_review_response_responder_id ON review_response(responder_id);
CREATE INDEX IF NOT EXISTS idx_coupon_usage_discount_code_used_at ON coupon_usage(discount_code_id, used_at);
CREATE INDEX IF NOT EXISTS idx_coupon_usage_customer_used_at ON coupon_usage(customer_id, used_at);
CREATE INDEX IF NOT EXISTS idx_customer_issue_report_customer_created_at
  ON customer_issue_report(customer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_customer_issue_report_booking_id ON customer_issue_report(booking_id);
CREATE INDEX IF NOT EXISTS idx_app_notification_recipient_created_at
  ON app_notification(recipient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_staff_shift_registration_staff_date
  ON staff_shift_registration(staff_id, work_date, start_time);
CREATE INDEX IF NOT EXISTS idx_staff_shift_registration_status_date
  ON staff_shift_registration(status, work_date, start_time);
CREATE UNIQUE INDEX IF NOT EXISTS ux_staff_shift_registration_exact_active_slot
  ON staff_shift_registration(staff_id, work_date, start_time, end_time)
  WHERE status IN ('PENDING', 'APPROVED');
CREATE UNIQUE INDEX IF NOT EXISTS ux_staff_attendance_working_shift
  ON staff_attendance(staff_id, shift_id)
  WHERE status = 'WORKING' AND shift_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_staff_attendance_staff_time
  ON staff_attendance(staff_id, check_in_time DESC);
CREATE INDEX IF NOT EXISTS idx_staff_attendance_status ON staff_attendance(status);
CREATE INDEX IF NOT EXISTS idx_facility_condition_report_room_created_at
  ON facility_condition_report(room_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_facility_condition_report_equipment_created_at
  ON facility_condition_report(equipment_id, created_at DESC) WHERE equipment_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_facility_condition_report_staff_created_at
  ON facility_condition_report(staff_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_facility_condition_report_maintenance
  ON facility_condition_report(maintenance_suggested, created_at DESC) WHERE maintenance_suggested = true;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'excl_booking_no_overlap') THEN
    ALTER TABLE booking
      ADD CONSTRAINT excl_booking_no_overlap
      EXCLUDE USING gist (
        room_id WITH =,
        tsrange(start_time, end_time, '[)') WITH &&
      )
      WHERE (status <> 'CANCELLED');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'excl_shift_staff_no_overlap') THEN
    ALTER TABLE "shift"
      ADD CONSTRAINT excl_shift_staff_no_overlap
      EXCLUDE USING gist (
        staff_id WITH =,
        tsrange(date + start_time, date + end_time, '[)') WITH &&
      );
  END IF;
END
$$;

COMMENT ON TABLE room_tier IS 'Homestay room categories such as Standard, Deluxe, and Family.';
COMMENT ON TABLE room IS 'Individual homestay rooms offered for booking.';
COMMENT ON TABLE equipment IS 'Room amenities and operational equipment such as Wi-Fi, air conditioner, TV, and water heater.';
COMMENT ON COLUMN booking.equipment_notes IS 'Amenities the guest asks staff to prepare or verify.';

INSERT INTO account (email, password_hash, role, email_verified, enabled)
VALUES (
  'admin@homestay.local',
  '$2a$10$GvWVKahyW48qvHRAsjGbYOXoFz3b/cDSykbxByfHGnCFw/oIvOuZS',
  'ADMIN',
  true,
  true
)
ON CONFLICT (email) DO UPDATE
SET password_hash = EXCLUDED.password_hash,
    role = EXCLUDED.role,
    email_verified = EXCLUDED.email_verified,
    enabled = EXCLUDED.enabled;

COMMIT;
