CREATE TABLE IF NOT EXISTS oauth_identity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  provider VARCHAR(32) NOT NULL,
  provider_subject VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  last_login_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT uq_oauth_identity_provider_subject UNIQUE (provider, provider_subject),
  CONSTRAINT uq_oauth_identity_account_provider UNIQUE (account_id, provider),
  CONSTRAINT chk_oauth_identity_provider CHECK (provider IN ('GOOGLE'))
);

CREATE INDEX IF NOT EXISTS idx_oauth_identity_account_id
  ON oauth_identity(account_id);
