BEGIN;

ALTER TABLE room
    ADD COLUMN IF NOT EXISTS image_url_2 VARCHAR(500),
    ADD COLUMN IF NOT EXISTS image_url_3 VARCHAR(500),
    ADD COLUMN IF NOT EXISTS image_url_4 VARCHAR(500);

CREATE TABLE IF NOT EXISTS common_amenity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    description VARCHAR(500) NOT NULL,
    icon_name VARCHAR(60) NOT NULL,
    image_url VARCHAR(500),
    display_order INT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

-- Mutable amenities are created and maintained from the admin application. Keeping
-- seed rows in a repeatable/manual migration would recreate amenities after deletion.

COMMIT;
