-- Run this once against an existing homestaydb database.

DO $$
BEGIN
  CREATE TYPE cong_thanh_toan AS ENUM ('VNPAY');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE trang_thai_giao_dich AS ENUM (
    'KHOI_TAO', 'CHO_THANH_TOAN', 'THANH_CONG', 'THAT_BAI', 'DA_HUY'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS giao_dich_thanh_toan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dat_phong_id int NOT NULL REFERENCES dat_phong(id),
  cong_thanh_toan cong_thanh_toan NOT NULL,
  ma_giao_dich varchar(100) UNIQUE NOT NULL,
  ma_giao_dich_cong varchar(100) UNIQUE,
  so_tien numeric(12,2) NOT NULL CHECK (so_tien >= 0),
  trang_thai trang_thai_giao_dich NOT NULL DEFAULT 'KHOI_TAO',
  ma_phan_hoi varchar(20),
  thoi_gian_thanh_toan timestamp,
  ngay_tao timestamp NOT NULL DEFAULT now(),
  ngay_cap_nhat timestamp NOT NULL DEFAULT now()
);
