-- Add the counter payment provider used by in-store cash checkout and
-- create backend-owned customer issue reports for /api/customer/report-issue.

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_provider') THEN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_enum e
            JOIN pg_type t ON t.oid = e.enumtypid
            WHERE t.typname = 'payment_provider'
              AND e.enumlabel = 'COUNTER'
        ) THEN
            ALTER TYPE payment_provider ADD VALUE 'COUNTER';
        END IF;
    ELSIF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'cong_thanh_toan') THEN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_enum e
            JOIN pg_type t ON t.oid = e.enumtypid
            WHERE t.typname = 'cong_thanh_toan'
              AND e.enumlabel = 'COUNTER'
        ) THEN
            ALTER TYPE cong_thanh_toan ADD VALUE 'COUNTER';
        END IF;
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS customer_issue_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL REFERENCES customer(id),
    booking_id INT REFERENCES booking(id),
    issue_type VARCHAR(30) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT chk_customer_issue_report_issue_type
        CHECK (issue_type IN ('ROOM', 'EQUIPMENT', 'PAYMENT', 'ACCOUNT', 'OTHER')),
    CONSTRAINT chk_customer_issue_report_status
        CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')),
    CONSTRAINT chk_customer_issue_report_description_not_blank
        CHECK (btrim(description) <> '')
);

CREATE INDEX IF NOT EXISTS idx_customer_issue_report_customer_created_at
    ON customer_issue_report (customer_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_customer_issue_report_booking_id
    ON customer_issue_report (booking_id);
