ALTER TABLE staff
    ADD COLUMN IF NOT EXISTS hourly_rate NUMERIC(12,2) NOT NULL DEFAULT 0;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_staff_hourly_rate_non_negative') THEN
        ALTER TABLE staff
            ADD CONSTRAINT chk_staff_hourly_rate_non_negative CHECK (hourly_rate >= 0);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS payroll_period (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pay_year INT NOT NULL,
    pay_month INT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    finalized_at TIMESTAMP,
    paid_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT ux_payroll_period_year_month UNIQUE (pay_year, pay_month),
    CONSTRAINT chk_payroll_period_month CHECK (pay_month BETWEEN 1 AND 12),
    CONSTRAINT chk_payroll_period_status CHECK (status IN ('DRAFT', 'FINALIZED', 'PAID'))
);

CREATE TABLE IF NOT EXISTS payroll_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_period_id BIGINT NOT NULL REFERENCES payroll_period(id) ON DELETE CASCADE,
    staff_id INT NOT NULL REFERENCES staff(id),
    work_hours NUMERIC(10,2) NOT NULL DEFAULT 0,
    hourly_rate NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_salary NUMERIC(14,2) NOT NULL DEFAULT 0,
    CONSTRAINT ux_payroll_item_period_staff UNIQUE (payroll_period_id, staff_id),
    CONSTRAINT chk_payroll_item_values_non_negative CHECK (
        work_hours >= 0 AND hourly_rate >= 0 AND total_salary >= 0
    )
);
