DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'shift_registration_status') THEN
        CREATE TYPE shift_registration_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS staff_shift_registration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INT NOT NULL REFERENCES staff(id),
    work_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    status shift_registration_status NOT NULL DEFAULT 'PENDING',
    reviewed_by_account_id INT REFERENCES account(id),
    reviewed_at TIMESTAMP,
    rejection_reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT chk_staff_shift_registration_time_range
        CHECK (start_time < end_time),
    CONSTRAINT chk_staff_shift_registration_decision_fields
        CHECK (
            (
                status = 'PENDING'
                AND reviewed_by_account_id IS NULL
                AND reviewed_at IS NULL
                AND rejection_reason IS NULL
            )
            OR (
                status = 'APPROVED'
                AND reviewed_by_account_id IS NOT NULL
                AND reviewed_at IS NOT NULL
                AND rejection_reason IS NULL
            )
            OR (
                status = 'REJECTED'
                AND reviewed_by_account_id IS NOT NULL
                AND reviewed_at IS NOT NULL
                AND rejection_reason IS NOT NULL
                AND btrim(rejection_reason) <> ''
            )
        )
);

CREATE INDEX IF NOT EXISTS idx_staff_shift_registration_staff_date
    ON staff_shift_registration(staff_id, work_date, start_time);

CREATE INDEX IF NOT EXISTS idx_staff_shift_registration_status_date
    ON staff_shift_registration(status, work_date, start_time);

CREATE UNIQUE INDEX IF NOT EXISTS ux_staff_shift_registration_exact_active_slot
    ON staff_shift_registration(staff_id, work_date, start_time, end_time)
    WHERE status IN ('PENDING', 'APPROVED');
