BEGIN;

CREATE TABLE IF NOT EXISTS review_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id INT NOT NULL REFERENCES review(id) ON DELETE CASCADE,
    image_url VARCHAR(500) NOT NULL,
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT chk_review_image_display_order CHECK (display_order BETWEEN 0 AND 3)
);

CREATE INDEX IF NOT EXISTS idx_review_image_review_display_order
    ON review_image(review_id, display_order, id);

COMMIT;
