CREATE TABLE IF NOT EXISTS app_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id INT NOT NULL REFERENCES account(id),
    type VARCHAR(60) NOT NULL,
    title VARCHAR(150) NOT NULL,
    content TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_app_notification_recipient_created_at
    ON app_notification(recipient_id, created_at DESC);
