BEGIN;

CREATE TABLE IF NOT EXISTS favorite_room (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    room_id INTEGER NOT NULL REFERENCES room(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uq_favorite_room_account_room UNIQUE (account_id, room_id)
);

CREATE INDEX IF NOT EXISTS idx_favorite_room_account_created_at
    ON favorite_room (account_id, created_at DESC);

COMMIT;
